books/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import *
from django.contrib.auth.decorators import login_required

app_name = 'books'

urlpatterns = [
    path('home/filter=<variable>', index, name='post-list'),
    path('post/<int:pk>/', post_detail, name='post-detail'),
    path('signup/', signup, name='signup'),
    path('search/', search, name='search'),
    path('create-new/', post_new, name='create-post'),
    path('edit/<int:pk>/', post_edit, name='post-edit'),
    path('<int:pk>/like/', PostLikeToggle.as_view(), name="like-toggle"),
    path('delete/post/<int:pk>/', post_delete, name='post-delete'),
    path('edit/post/<int:pk>', post_edit, name='post-edit'),
    path('(<int:pk>/delete-comment/', delete_comment, name='delete-comment'),
    path('profile/<int:pk>/', profile, name='user-profile'),
    path('blogs/', blog_list, name='blog-list'),
    path('create-blog/', blog_new, name='create-blog'),
    path('delete/blog/<int:pk>/', blog_delete, name='blog-delete'),
    path('edit/blog/<int:pk>', blog_edit, name='blog-edit'),
    path('blog/<int:pk>/', blog_detail, name='blog-detail'),
    path('favotire/post/<int:pk>', AddToFavorite.as_view(), name='add-favorite'),
    path('delete-favotire/post/<int:pk>', RemoveFromFavorite.as_view(), name='remove-favorite'),
    path('chat/', chat, name='chat'),
    path('delete-message/<int:pk>/chat', globa_delete, name='global-delete'),
    path('user-settings/', user_settings, name='user-settings'),
    path('change-password/', change_password, name='change-password'),
    path('delete-user/', delete_user, name="delete-user"),
    path('new-chapter/post/<int:pk>/', chapter_new, name='create-chapter'),
    path('edit-chapter/<int:pk>/', chapter_edit, name='chapter-edit'),
    path('delete/chapter/<int:pk>/', chapter_delete, name='chapter-delete'),
    path('chapter/<int:pk>', chaper_detail, name='chapter-detail'),
    path('notes/', notes_list, name='notes'),


]

kursovaMVC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('^oauth/', include('social_django.urls', namespace='social')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT);

templates/pages/blog-detail.html
{% extends 'index.html' %}
{% load static %}
{% load staticfiles %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <style>

	.post_img{
	height: auto; width: 100%;
	}

	.like{height: 25px; width: auto; opacity: 0.7;}

	.shareico{height: 40px; width: auto; margin-right: 0.5em;}

	.ico{height: 20px; width: auto; margin-right: 0.2em; }

	#likeamount{margin-left: 10px;}

	#date{font-style: italic; right: 0; left: 100%;}

	.post{border: #e3e5e8 1px solid;}

	p{padding-left: 1em; padding-right: 1em;}

	textarea{width:100%; border: #e3e5e8 1px solid;}

	#comment{background-color: #f2f4f7; margin-bottom: 0.3em; width:100%;}

	button{width: 100%; background-color: #e7e7e7; color: black; border: none;}
	button:hover {
	  background-color: white
	}

	#comment_section{display: none;}

	#send_btn img
	{
		position: relative;
	    top: 50%;
	    left: 50%;
	    transform:translate(-50%, -50%);
	}

	@media only screen and (max-width: 500px) {
	  #del_btn {
		text-align: left;
	  }
	}

</style>

    <div class="container" style="margin-top:2%">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 post">



			<div class="row">
			<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12"><h3>{{ post.title }}</h3></div>
			<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12" style="text-align: right"><label id="date">{{ post.timestamp }}</label></div>
			</div><br>
			<div class="row">
				<p style="white-space: pre-line;  background-color: rgba(255, 255,255, 0.3)">{{ post.content }}</p><br>
			</div>
			<p style="font-style: italic;">by <b>{{ post.author.username }}</b></p>
			<form method="post" style="margin-bottom: 4em">
                    {% csrf_token %}
                    {% if request.user.is_authenticated %}
                        {% for field in form %}
                            {{ field }}
                        {% endfor %}

                        <div id="send_btn"><input  type="submit" value="Submit" class="btn btn-outline-success" style="float: right; margin-top: 1em "></div>
                    {% else %}
                        <p style="color:red; text-align: center"> You're not authenticated to write a comment<p>
                    {% endif %}
                </form>


			<div class="row"><button onclick="show()"><label id="show_comments">Show comments</label></button></div>
			<div id="comment_section">
            {% if comments %}
                {% for obj in comments %}
				<div class="container" id="comment">
					<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"><label><b><a style="color: red" href="{% url 'books:user-profile' obj.author.pk %}" >{{ obj.author.username }}</a></b></label></div>
								<div class="col-lg-4 col-md-4 col-sm-3 col-7" style="text-align: right" id="del_btn">
									{% if request.user == obj.author %}<a href="{% url 'books:delete-comment' obj.pk%}">
										<img src={% static 'img/delete.png' %} class="ico">
									</a>{% endif %}
								</div>
							<div class="col-lg-2 col-md-2 col-sm-3 col-5" style="text-align: right"><label id="date" style="font-size: 0.7em;">{{ obj.timestamp }}</label> </div>
					</div>
					<div class="row"><p>{{ obj.text }}</p></div>
				</div>
                {% endfor %}
            {% else %}
                <p style="text-align: center"><strong>No comments yet. You can be the first!</strong></p>
            {% endif %}
			</div>
		</div>
	</div>

	<script>
		function show()
		{
			if(document.getElementById("comment_section").style.display == "none")
			{
				document.getElementById("comment_section").style.display = "block";
				document.getElementById("show_comments").innerHTML = "Hide comments";
			}

			else
			{
				document.getElementById("comment_section").style.display = "none";
				document.getElementById("show_comments").innerHTML = "Show comments";
			}
		}
	</script>
{% endblock %}

templates/pages/blog-list.html
{% extends 'index.html' %}


{% block content %}
   <style>
        .thumbnail {
          position: relative;
          width: auto;
          height: 10em;
          overflow: hidden;
        }
        .thumbnail img {
          position: absolute;
          left: 50%;
          top: 50%;
          height: auto;
          width: 100%;
          -webkit-transform: translate(-50%,-50%);
              -ms-transform: translate(-50%,-50%);
                  transform: translate(-50%,-50%);
        }
        .thumbnail img.portrait {
          width: 100%;
          height: auto;
        }
        p {
             overflow: hidden;
           text-overflow: ellipsis;
           display: -webkit-box;
           line-height: 20px;     /* fallback */
           max-height: 100px;      /* fallback */
           -webkit-line-clamp: 4; /* number of lines to show */
           -webkit-box-orient: vertical;
        }
        label{color: palevioletred;}
        a:hover{text-decoration: none;}
        #stuff{margin-bottom: 5%; border: #c7cecc 2px solid; height: 97%; margin-bottom: 4%;}

        .container{padding-top: 2%; padding-bottom: 2%;}

		.row{border: #f2f4f7 2px solid; margin-bottom: 1em;}
    </style>
    <div class="container">
            {% for obj in posts %}
                <div class="row">

				<div class="col-12" style="background-color:#f2f4f7;">
					<div class="row">
                        <div class="col-9"><a href="{% url 'books:blog-detail' obj.pk %}"><h3>{{ obj.title }}</h3></a></div>
                         <div class="col-3" style="color:red; padding-top: 0.5em; text-align:right;">by <b><a style="color: red" href="{% url 'books:user-profile' obj.author.pk %}" >{{ obj.author.username }}</a></b></div>
                    </div>
					<p>{{ obj.content }}</p>
					<label>{{ obj.created }}</label>
				</div>
		</div>
            {% endfor %}
    </div>
    <div class="col-6 offset-3 text-center" style="margin-top: 1.5rem;">
        {% include 'pagination.html' %}
     </div>

{% endblock %}

templates/pages/chapter.html
{% extends 'index.html' %}
{% load static %}
{% load staticfiles %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

    <style>

	.like{height: 25px; width: auto; opacity: 0.7;}

	.shareico{height: 40px; width: auto; margin-right: 0.5em;}

	.ico{height: 20px; width: auto; margin-right: 0.2em; }

	#likeamount{margin-left: 10px;}

	#date{font-style: italic; right: 0; left: 100%;}

	.post{border: #e3e5e8 1px solid;}

	p{padding-left: 1em; padding-right: 1em;}

	textarea{width:100%; border: #e3e5e8 1px solid;}

	#comment{background-color: #f2f4f7; margin-bottom: 0.3em; width:100%;}

	button{width: 100%; background-color: #e7e7e7; color: black; border: none;}
	button:hover {
	  background-color: white
	}

	#comment_section{display: none;}

	#send_btn img
	{
		position: relative;
	    top: 50%;
	    left: 50%;
	    transform:translate(-50%, -50%);
	}

	@media only screen and (max-width: 500px) {
	  #del_btn {
		text-align: left;
	  }
	}
</style>

     <div class="container">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 post">

            <div class="row" style="text-align: center; display: block;"><h3>{{ chapter.title }}</h3></div>

			<div class="row">
				<p style="white-space: pre-line;  background-color: rgba(255, 255,255, 0.3)">{{ chapter.content }}</p><br>
			</div>
            <hr>
			<div class="row">
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12"><p style="font-style: italic;">by <b>{{ chapter.book.author.username }}</b></p></div>
			    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12" style="text-align: right;"><label id="date">{{ chapter.timestamp }}</label></div>
			</div>
            {% if user == chapter.book.author %}
            <div class="col-12" style="text-align: right">
                        <a href="{% url 'books:chapter-edit' chapter.pk %}"><span style="padding-right: 1%;">edit</span></a>
                        <a href="{% url 'books:chapter-delete' chapter.pk %}" onclick="return confirm('Do you really want to delete this post?')"><span style="color: red;">delete</span></a>
            </div>
            {% endif %}
            <br>


		</div>
	</div>

{% endblock %}

templates/pages/chat.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Global Chat{% endblock %}
{% block content %}
  <style>



	.ico{height: 20px; width: auto; margin-right: 0.2em; }

	#date{font-style: italic; right: 0; left: 100%;}


	p{padding-left: 1em; padding-right: 1em;}

	textarea{width:100%; border: #e3e5e8 1px solid;}

	#comment{background-color: #f2f4f7; margin-bottom: 0.3em; width:100%;}

	button{width: 100%; background-color: #e7e7e7; color: black; border: none;}
	button:hover {
	  background-color: white
	}


	#send_btn img
	{
		position: relative;
	    top: 50%;
	    left: 50%;
	    transform:translate(-50%, -50%);
	}

	@media only screen and (max-width: 500px) {
	  #del_btn {
		text-align: left;
	  }
	}

</style>
<div class="container" style="background-color: rgba(255,255,255,0.6); padding-bottom: 2% ">
			<div id="comment_section">
            {% if comments %}
                {% for obj in comments %}
				<div class="container" id="comment">
					<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"><label><b><a style="color: red" href="{% url 'books:user-profile' obj.author.pk %}" >{{ obj.author.username }}</a></b></label></div>
								<div class="col-lg-4 col-md-4 col-sm-3 col-7" style="text-align: right" id="del_btn">
									{% if request.user == obj.author or user.is_staff %}<a href="{% url 'books:global-delete' obj.pk%}">
										<img src={% static 'img/delete.png' %} class="ico">
									</a>{% endif %}
								</div>

							<div class="col-lg-2 col-md-2 col-sm-3 col-5" style="text-align: right"><label id="date" style="font-size: 0.7em;">{{ obj.timestamp }}</label> </div>
					</div>
					<div class="row"><p>{{ obj.text }}</p></div>
				</div>
                {% endfor %}
            {% else %}
                <p style="text-align: center"><strong>No comments yet. You can be the first!</strong></p>
            {% endif %}

               <form method="post" style="margin-bottom: 4em">
                    {% csrf_token %}
                    {% if request.user.is_authenticated %}
                        {% for field in form %}
                            {{ field }}
                        {% endfor %}

                        <div id="send_btn"><input  type="submit" value="Submit" class="btn btn-outline-success" style="float: right; margin-top: 1em "></div>
                    {% else %}
                        <p style="color:red; text-align: center"> You're not authenticated to write a comment<p>
                    {% endif %}
                </form>

			</div>
		</div>
    </div>
{% endblock %}

templates/pages/post-detail.html
{% extends 'index.html' %}
{% load static %}
{% load staticfiles %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <style>

	.post_img{
	height: auto; width: 100%;
	}

	.like{height: 25px; width: auto; opacity: 0.7;}

	.shareico{height: 40px; width: auto; margin-right: 0.5em;}

	.ico{height: 20px; width: auto; margin-right: 0.2em; }

	#likeamount{margin-left: 10px;}

	#date{font-style: italic; right: 0; left: 100%;}

	.post{border: #e3e5e8 1px solid;}

	p{padding-left: 1em; padding-right: 1em;}

	textarea{width:100%; border: #e3e5e8 1px solid;}

	#comment{background-color: #f2f4f7; margin-bottom: 0.3em; width:100%;}

	button{width: 100%; background-color: #e7e7e7; color: black; border: none;}
	button:hover {
	  background-color: white
	}

	#comment_section{display: none;}

	#send_btn img
	{
		position: relative;
	    top: 50%;
	    left: 50%;
	    transform:translate(-50%, -50%);
	}

	@media only screen and (max-width: 500px) {
	  #del_btn {
		text-align: left;
	  }
	}

    a:hover{text-decoration: none;}
</style>

    <div class="container">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 post">

			<img  style="width: 50%; margin: auto; display: block;" src='/media/{{ post.image }}'  class="post_img"/>

			<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12"><a  href={% url 'books:like-toggle' post.pk %}><img src={% static 'img/heart.png' %} class="like"></a> <label id="likeamount"><b>{{ post.likes.count }}</b></label></div>
			<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12" style="text-align: right"><label id="date">{{ post.created }}</label></div>
			</div><br>
        {% if favorite == 3 %}
            <a href="{% url 'books:remove-favorite' post.pk %}">Remove from favorite</a>
        {% elif favorite == 2 %}
             <a href="{% url 'books:add-favorite' post.pk %}">Add to favorite</a>
        {%else %}

        {%  endif%}
			<div class="row">
				<p style="white-space: pre-line;  background-color: rgba(255, 255,255, 0.3)">{{ post.description }}</p><br>
			</div>
        <div class="row">
            <div class="col-7"><p style="font-style: italic;">by <b>{{ post.author.username }}</b></p></div>
             {% if user == post.author %}
                    <div class="col-5" style="text-align: right;">
                        <a href="{% url 'books:post-edit' post.pk %}"><span style="padding-right: 1%;">edit post</span></a>
                        <a href="{% url 'books:post-delete' post.pk %}" onclick="return confirm('Do you really want to delete this post?')"><span style="color: red;">delete post</span></a>
                    </div>
            {% endif %}
        </div>

            <div class="col-12" style="margin-bottom: 2em;">
                <h4 class="text-center">Chapters</h4>
            <ul class="list-group list-group-flush">
            {% if chapters %}


                    {% for item in chapters %}
                        <a href="{% url 'books:chapter-detail' item.pk %}" style=" color:black;"><li class="list-group-item text-center text-capitalize" ><strong>{{ item.title }}</strong></li></a>
                    {% endfor %}
                {% if user == post.author %}
                    <a href="{% url 'books:create-chapter' post.pk %}"><li class="list-group-item text-center"><strong>Create new chapter</strong></li></a>
                {% endif %}
            {% else %}

                <li class="text-center list-group-item"><strong>There is no chapters yet!</strong></li>
                {% if user == post.author %}
                <a href="{% url 'books:create-chapter' post.pk %}"><li class="list-group-item text-center"><strong>Create new chapter</strong></li></a>
                {% endif %}
            {% endif %}
            </ul>
            <hr>
            </div>

              <form method="post" style="margin-bottom: 4em">
                    {% csrf_token %}
                    {% if request.user.is_authenticated %}
                        {% for field in form %}
                            {{ field }}
                        {% endfor %}

                        <div id="send_btn"><input  type="submit" value="Submit" class="btn btn-outline-success" style="float: right; margin-top: 1em "></div>
                    {% else %}
                        <p style="color:red"> You're not authenticated to write a comment<p>
                    {% endif %}
                </form>


			<div class="row"><button onclick="show()"><label id="show_comments">Show comments</label></button></div>
			<div id="comment_section">
            {% if comments %}
                {% for obj in comments %}
				<div class="container" id="comment">
					<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"><label><b><a style="color: red" href="{% url 'books:user-profile' obj.author.pk %}" >{{ obj.author.username }}</a></b></label></div>
								<div class="col-lg-4 col-md-4 col-sm-3 col-7" style="text-align: right" id="del_btn">
									{% if request.user == obj.author %}<a href="{% url 'books:delete-comment' obj.pk%}" onclick="return confirm('Do you really want to delete this comment?')">
										<img src={% static 'img/delete.png' %} class="ico">
									</a>{% endif %}
								</div>
							<div class="col-lg-2 col-md-2 col-sm-3 col-5" style="text-align: right"><label id="date" style="font-size: 0.7em;">{{ obj.timestamp }}</label> </div>
					</div>
					<div class="row"><p>{{ obj.text }}</p></div>
				</div>
                {% endfor %}
            {% else %}
                <p style="text-align: center"><strong>No comments yet. You can be the first!</strong></p>
            {% endif %}
			</div>
		</div>
	</div>

	<script>
		function show()
		{
			if(document.getElementById("comment_section").style.display == "none")
			{
				document.getElementById("comment_section").style.display = "block";
				document.getElementById("show_comments").innerHTML = "Hide comments";
			}

			else
			{
				document.getElementById("comment_section").style.display = "none";
				document.getElementById("show_comments").innerHTML = "Show comments";
			}
		}
	</script>
{% endblock %}

templates/pages/post-edit.html
{% extends 'index.html' %}
{% block title %}Edit Post{% endblock %}
{% block content %}
     <div id= "reg" class="container">
        <h1>Edit</h1>
        <form method="POST" style = " margin-bottom: 7%" class="post-form" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
            {% for field in form %}
            <h5>{{ field.label_tag }}</h5>
              {{ field }}<br>
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
            {% endfor %}
            <button id="buttonS" type="submit" class="btn btn-outline-success" style = "  float: right">Save</button>

        </form>
     </div>
{% endblock %}

templates/pages/post-list.html
{% extends 'index.html' %}


{% block content %}
   <style>
        .thumbnail {
          position: relative;
          width: auto;
          height: 10em;
          overflow: hidden;
        }
        .thumbnail img {
          position: absolute;
          left: 50%;
          top: 50%;
          height: auto;
          width: 100%;
          -webkit-transform: translate(-50%,-50%);
              -ms-transform: translate(-50%,-50%);
                  transform: translate(-50%,-50%);
        }
        .thumbnail img.portrait {
          width: 100%;
          height: auto;
        }
        p {
             overflow: hidden;
           text-overflow: ellipsis;
           display: -webkit-box;
           line-height: 20px;     /* fallback */
           max-height: 100px;      /* fallback */
           -webkit-line-clamp: 4; /* number of lines to show */
           -webkit-box-orient: vertical;
        }
        label{color: palevioletred;}
        a:hover{text-decoration: none;}
        #stuff{margin-bottom: 5%; border: #c7cecc 2px solid; height: 97%; margin-bottom: 4%;}

        .container{padding-top: 2%; padding-bottom: 2%;}
		.row{ margin-bottom: 1em;}
    </style>
    <div class="container">
    {% if notes %}
        <h3 class="text-center">It's your notes!</h3>
        <hr>
    {% endif %}
    {% if items and not notes %}
        <div class="row">
            <h5>Filter by:</h5>
            <a href="{% url 'books:post-list' '-created' %}">date</a>,
            <a href="{% url 'books:post-list' 'title' %}">name</a>,
            <a href="{% url 'books:post-list' '-likes' %}">likes</a>
        </div>
    {% endif %}
    {% if items  %}
            {% for obj in items %}
                <div class="row">
				<div class="col-3">
					<div class="thumbnail">
                        <img class="post_pic" src="{{ obj.image.url }}"  >
					</div>
				</div>
				<div class="col-9" style="background-color:#f2f4f7;">
					<div class="row">
          <div class="col-9"><a href="{% url 'books:post-detail' obj.pk %}"><h3>{{ obj.title }}</h3></a></div>
          <div class="col-3" style="color:red; padding-top: 0.5em; text-align:right;">by <b><a style="color: red" href="{% url 'books:user-profile' obj.author.pk %}" >{{ obj.author.username }}</a></b></div>
          </div>
					<p>{{ obj.description }}</p>
					<label>{{ obj.created }}</label>
				</div>
		</div>
            {% endfor %}
        {% else %}
        <h3 class="text-center">There is no books yet!</h3>
    {% endif %}
    </div>
    <div class="col-6 offset-3 text-center" style="margin-top: 1.5rem;">
        {% include 'pagination.html' %}
     </div>

{% endblock %}