books/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import *
from django.contrib.auth.decorators import login_required

app_name = 'books'

urlpatterns = [
    path('home/filter=<variable>', index, name='post-list'),
    path('post/<int:pk>/', post_detail, name='post-detail'),
    path('signup/', signup, name='signup'),
    path('search/', search, name='search'),
    path('create-new/', post_new, name='create-post'),
    path('edit/<int:pk>/', post_edit, name='post-edit'),
    path('<int:pk>/like/', PostLikeToggle.as_view(), name="like-toggle"),
    path('delete/post/<int:pk>/', post_delete, name='post-delete'),
    path('edit/post/<int:pk>', post_edit, name='post-edit'),
    path('(<int:pk>/delete-comment/', delete_comment, name='delete-comment'),
    path('profile/<int:pk>/', profile, name='user-profile'),
    path('blogs/', blog_list, name='blog-list'),
    path('create-blog/', blog_new, name='create-blog'),
    path('delete/blog/<int:pk>/', blog_delete, name='blog-delete'),
    path('edit/blog/<int:pk>', blog_edit, name='blog-edit'),
    path('blog/<int:pk>/', blog_detail, name='blog-detail'),
    path('favotire/post/<int:pk>', AddToFavorite.as_view(), name='add-favorite'),
    path('delete-favotire/post/<int:pk>', RemoveFromFavorite.as_view(), name='remove-favorite'),
    path('chat/', chat, name='chat'),
    path('delete-message/<int:pk>/chat', globa_delete, name='global-delete'),
    path('user-settings/', user_settings, name='user-settings'),
    path('change-password/', change_password, name='change-password'),
    path('delete-user/', delete_user, name="delete-user"),
    path('new-chapter/post/<int:pk>/', chapter_new, name='create-chapter'),
    path('edit-chapter/<int:pk>/', chapter_edit, name='chapter-edit'),
    path('delete/chapter/<int:pk>/', chapter_delete, name='chapter-delete'),
    path('chapter/<int:pk>', chaper_detail, name='chapter-detail'),
    path('notes/', notes_list, name='notes'),


]

kursovaMVC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('^oauth/', include('social_django.urls', namespace='social')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT);

templates/index.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}LitLib{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src= "https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity= "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin= "anonymous" ></script> <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity= "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin= "anonymous" ></script> <script src= "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity= "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin= "anonymous" ></script>

</head>
<body style=" font-family:'Bookman Old Style' ">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'books:post-list' '-created'%}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link" href={% url 'books:blog-list' %}>Blogs<span class="sr-only">(current)</span></a>
      </li>
    <li class="nav-item active">
        <a class="nav-link" href={% url 'books:chat' %}>Chat <span class="sr-only">(current)</span></a>
      </li>
   {% if user.is_authenticated %}

      <li class="nav-item dropdown " >
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
            <a class="dropdown-item" href="{% url 'books:user-profile' request.user.pk %}">Profile</a>
            <a class="dropdown-item" href="{% url 'books:notes' %}">Notes</a>
            <a class="dropdown-item" href="{% url 'books:create-post' %}">Create book</a>
            <a class="dropdown-item" href="{% url 'books:create-blog' %}">Create blog</a>
            <a class="dropdown-item" href="{% url 'books:user-settings' %}">Settings</a>
            {% if user.is_superuser %}
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin page</a>
                {% endif %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}?next=/home/filter=-created">Logout</a>
        </div>
      </li>
    {% else %}
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'books:signup' %}">SignUp <span class="sr-only">(current)</span></a>
      </li>
    {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET"  action="{% url 'books:search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" value="{{ request.GET.q }}" aria-label="Search">
      <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">
    </form>
  </div>
</nav>
    {% block content %}
        <!-- templates are supposed to be rendered here-->
    {% endblock %}
</body>
<hr>
<footer class="text-center">Developed by: ©Michael Benko, LNU 2019</footer>
</html>

templates/pagination.html
{% if items.has_other_pages %}
    <div class="col-6 offset-3 text-center pagination-set">
        <nav aria-label="">
            <ul class="pagination">
                {% if items.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ items.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link"><span>&laquo;</span></a></li>
                {% endif %}
                {% for i in page_range %}
                    {% if items.number == i %}
                        <li class="page-item active"><a class="page-link" href="#">{{ i }} <span
                                class="sr-only">(current)</span></a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}{% if query %}&q={{ query }}{% endif %}</a></li>
                    {% endif %}
                {% endfor %}
                {% if items.has_next %}
                    <li class="page-item"><a class="page-link" aria-label="Next"
                                             href="?page={{ items.next_page_number }}{% if query %}&q={{ query }}{% endif %}">&raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link"><span>&raquo;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}