books/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import *
from django.contrib.auth.decorators import login_required

app_name = 'books'

urlpatterns = [
    path('home/filter=<variable>', index, name='post-list'),
    path('post/<int:pk>/', post_detail, name='post-detail'),
    path('signup/', signup, name='signup'),
    path('search/', search, name='search'),
    path('create-new/', post_new, name='create-post'),
    path('edit/<int:pk>/', post_edit, name='post-edit'),
    path('<int:pk>/like/', PostLikeToggle.as_view(), name="like-toggle"),
    path('delete/post/<int:pk>/', post_delete, name='post-delete'),
    path('edit/post/<int:pk>', post_edit, name='post-edit'),
    path('(<int:pk>/delete-comment/', delete_comment, name='delete-comment'),
    path('profile/<int:pk>/', profile, name='user-profile'),
    path('blogs/', blog_list, name='blog-list'),
    path('create-blog/', blog_new, name='create-blog'),
    path('delete/blog/<int:pk>/', blog_delete, name='blog-delete'),
    path('edit/blog/<int:pk>', blog_edit, name='blog-edit'),
    path('blog/<int:pk>/', blog_detail, name='blog-detail'),
    path('favotire/post/<int:pk>', AddToFavorite.as_view(), name='add-favorite'),
    path('delete-favotire/post/<int:pk>', RemoveFromFavorite.as_view(), name='remove-favorite'),
    path('chat/', chat, name='chat'),
    path('delete-message/<int:pk>/chat', globa_delete, name='global-delete'),
    path('user-settings/', user_settings, name='user-settings'),
    path('change-password/', change_password, name='change-password'),
    path('delete-user/', delete_user, name="delete-user"),
    path('new-chapter/post/<int:pk>/', chapter_new, name='create-chapter'),
    path('edit-chapter/<int:pk>/', chapter_edit, name='chapter-edit'),
    path('delete/chapter/<int:pk>/', chapter_delete, name='chapter-delete'),
    path('chapter/<int:pk>', chaper_detail, name='chapter-detail'),
    path('notes/', notes_list, name='notes'),


]

kursovaMVC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('^oauth/', include('social_django.urls', namespace='social')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT);

templates/user/change-password.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container" style="padding-top: 3%;margin-bottom: 4em">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success" style="float: right ">Submit</button>
        </form>
    </div>
{% endblock%}

templates/user/profile.html
{% extends 'index.html' %}
{% load static %}
{% load staticfiles %}
{% block title %}{{ user.username }}{% endblock %}
{% block content %}
    <style>

	.thumbnail {
  position: relative;
  width: 100%;
  height: 20em;
  overflow: hidden;
}
.thumbnail img {
  position: absolute;
  left: 50%;
  top: 50%;
  height: 100%;
  width: auto;
  -webkit-transform: translate(-50%,-50%);
      -ms-transform: translate(-50%,-50%);
          transform: translate(-50%,-50%);


}
.thumbnail img.portrait {
  width: 100%;
  height: auto;
}

p{font-size: 1.2em;}

    #cont{
             overflow: hidden;
           text-overflow: ellipsis;
           display: -webkit-box;
           line-height: 20px;     /* fallback */
           max-height: 100px;      /* fallback */
           -webkit-line-clamp: 4; /* number of lines to show */
           -webkit-box-orient: vertical;
        }
.shareico{height: 40px; width: auto; margin-right: 0.5em;}

</style>
    <div class="container" >
		<div class="row" >
			<div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
				<div class="thumbnail">
					<img class="post_pic" src='/media/{{ profile.avatar }}' >
				</div>
			</div>
			<div class="col-lg-8 col-md-6 col-sm-12 col-xs-12" style="background-color: #f2f4f7; padding-left: 20px;">
                <h3>{{ user.username }}<span style="float: right;"><a href="{% url '' request.user.pk%}">delete profile</a></span></h3>
				<p>{{ user.first_name }} {{ user.last_name }}</p>
				<div class="row"><img src={% static 'img/phone.png' %} class="shareico"><p>{{ profile.phone }}</p></div>
				<div class="row"><img src={% static 'img/website.png' %} class="shareico"><p>{{ profile.site }}</p></div>
				<div class="row"><img src={% static 'img/skype.png' %} class="shareico"><p>{{ profile.skype }}</p></div>
				<div class="row"><img src={% static 'img/instagram.png' %} class="shareico"><p>{{ profile.instagram }}</p></div>
				<div class="row"><img src={% static 'img/email.png' %} class="shareico"><p>{{ user.email }}</p></div>
			</div>
		</div>
    <hr>
    <h3 style="text-align: center">Favorite books</h3>
    <hr>
    {% if favorites %}
        {% for obj in favorites %}
                <div class="row">

				<div class="col-12" style="background-color:#f2f4f7;">
					<div class="row">
                        <div class="col-9"><a href="{% url 'books:post-detail' obj.book.pk %}"><h3>{{ obj.book.title }}</h3></a></div>
                         <div class="col-3" style="color:red; padding-top: 0.5em; text-align:right;">by <b>{{ obj.book.author.username }}</b></div>
                    </div>
					<p id="cont">{{ obj.book.content }}</p>
					<label>{{ obj.book.created }}</label>
				</div>
		</div>
            {% endfor %}
	</div>
    {% else %}
        <p style="text-align: center ">There is no favorite books yet!</p>
    {% endif %}
{% endblock %}

templates/user/user-settings.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container" style="padding-top: 3%; margin-bottom: 4em">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="{% url 'books:change-password'%}">Change password</a><br><br>
            <button type="submit" class="btn btn-success" style="float: right">Submit</button>
        </form>
        <a href = '{% url 'books:delete-user' %}' class=" btn btn-danger" onclick="return confirm('Do you really want to delete this post?')"> Delete Page</a>
    </div>
{% endblock%}